ports:
  http_port: 8000
  https_port: 8443

logger:
  level: INFO
  output_std: true
  output_file: "./test_logfile.log"
  append_output: true

handler:
  content_root: "../test/web_content/deeper_webpage"
  cache_enabled: true

security: 
  cert_path: "../test/security/localhost_cert.pem"
  priv_key_path: "../test/security/localhost_key.pem"
